name: conda38omero
channels:
 - ome
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - python=3.8
 - pip
 - pip:
   - remote-ikernel
   - ipykernel
   - numpy
   - pandas
   - scikit-image
   - scikit-learn
   - opencv-python
   - omero-py