name: omesliccv3_env
channels:
 - ome
 - conda-forge
 - defaults
dependencies:
 - python=3.10
 - pip
 - numpy
 - pandas
 - scikit-image
 - scikit-learn
 - imagecodecs>=2023.3.16
 - numcodecs
 - dask
 - tifffile>=2023.9.26
 - ome-zarr
 - aiohttp
 - rsa
 - tqdm
 - psutil
 - PyYAML
 - Pillow
 - imageio
 - validators
 - toml
 - pip:
   - opencv-python
   - xmltodict
   - zarr==3.0.0a0
   - "--editable=git+https://github.com/will-moore/ome-zarr-py.git@zarr_v3_support#egg=ome-zarr"
