name: omeslicc-env
channels:
 - zacsimile
 - ome
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - python=3.12
 - numpy
 - pandas
 - scikit-image
 - scikit-learn
 - imagecodecs>=2023.3.16
 - numcodecs
 - dask
 - tifffile>=2023.9.26
 - zarr
 - ome-zarr
 - aiohttp
 - rsa
 - tqdm
 - psutil
 - PyYAML
 - Pillow
 - imageio
 - validators
 - toml
 - zeroc-ice
 - pip
 - pip:
   - omero-py
   - python-bioformats
   - opencv-python
   - xmltodict