name: omeslicc_env
channels:
 - zacsimile
 - ome
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - python=3.9
 - pip
 - numpy
 - pandas
 - scikit-image
 - scikit-learn
 - imagecodecs
 - numcodecs
 - tifffile
 - zarr
 - ome-zarr
 - aiohttp
 - omero-py
 - rsa
 - tqdm
 - psutil
 - PyYAML
 - Pillow
 - imageio
 - matplotlib
 - validators
 - toml
 - pip:
   - opencv-python
   - xmltodict
   - python-bioformats