input:
  # omero - Omero server address
  omero: ssl://omero.server
  # folder - input folder
  #folder: /folder/

  # type - project or image
  type: project
  #type: image

  # ids - project or image id(s)
  ids: 0

  # labels - required Omero metadata labels
  labels: [label1,label2]

output:
  folder: output/images
  format: ome.tiff
  channels: combine
  # channels: split
  tile_size: [256, 256]
  compression: ['JPEGXR_NDPI', 75]
  npyramid_add: 3
  pyramid_downsample: 4.0
  csv: resources/csv/labels.csv

# actions can be: info, thumbnail, convert, labels
actions: [convert, labels]

credentials:
  # for encoding/decoding (in private space):
  private_key: ~/omero.pri.key   # note ~ doesn't work from container
  public_key: ~/omero.pub.key   # note ~ doesn't work from container
  # encoded credentials (in public space):
  credentials: .omero_credentials

log:
  filename: log/omeslicc.log
  log_format: '%(asctime)s %(levelname)s: %(message)s'
